dist: trusty

language: node_js

node_js:
  - "9.3.0"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install software-properties-common -y -qq
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo add-apt-repository -y ppa:ethereum/ethereum-dev
  - sudo apt-get update -qq
  - sudo apt-get install geth -y -qq
  
install:
  - npm install
  - nohup npm start test.ganache.run &
  - npm start migrateContracts.fetchFromArc
  - npm start migrateContracts
  
script:
  - npm start lint
  - npm start test.automated

notifications:
  slack: daostack:fGuaFPsiQiV5mgmzRcSzbYqw
