site_name: DAOstack Arc.js Documentation
repo_url: https://github.com/daostack/arc.js/
repo_name: daostack/arc.js
site_description: A JavaScript library for interacting with @daostack/arc ethereum smart contracts
docs_dir: docs
extra_templates:
- index.html
markdown_extensions:
- admonition
- pymdownx.superfences
- codehilite:
    linenums: true
- toc:
    permalink: true
theme:
  name: 'material'
  favicon: 'img/favicon.ico'
  palette:
    primary: 'teal'
    accent: 'amber'
extra:
  social:
  - type: 'github'
    link: 'https://github.com/daostack/arc.js'
  - type: 'slack'
    link: 'https://daostack.slack.com'
  - type: 'telegram'
    link: 'https://t.me/daostackcommunity'

pages:
- 'Overview': Home.md
- 'Configuration': 'Configuration.md'
- 'DAOs': 'Daos.md'
- 'Contract Wrappers': 'Wrappers.md'
- 'Schemes, Proposals and Voting Machines': 'Proposals.md'
- 'Events': 'Events.md'
- 'Tracking Transactions': 'Transactions.md'
- 'Scripts': 'Scripts.md'
- 'Contract Migration': 'Migration.md'
- 'Using GanacheDb': 'GanacheDb.md'
- 'API Reference': 
  - Index : "api/README.md"
  # append output of `npm start docs.api.createPagesList` here:
  - AbsoluteVoteWrapper : 'api/classes/AbsoluteVoteWrapper.md'
  - AccountService : 'api/classes/AccountService.md'
  - ArcTransactionAgreementResult : 'api/classes/ArcTransactionAgreementResult.md'
  - ArcTransactionDataResult : 'api/classes/ArcTransactionDataResult.md'
  - ArcTransactionProposalResult : 'api/classes/ArcTransactionProposalResult.md'
  - ArcTransactionResult : 'api/classes/ArcTransactionResult.md'
  - AvatarService : 'api/classes/AvatarService.md'
  - ConfigService : 'api/classes/ConfigService.md'
  - ContractWrapperBase : 'api/classes/ContractWrapperBase.md'
  - ContractWrapperFactory : 'api/classes/ContractWrapperFactory.md'
  - ContributionRewardWrapper : 'api/classes/ContributionRewardWrapper.md'
  - ControllerService : 'api/classes/ControllerService.md'
  - DAO : 'api/classes/DAO.md'
  - DaoCreatorFactoryType : 'api/classes/DaoCreatorFactoryType.md'
  - DaoCreatorWrapper : 'api/classes/DaoCreatorWrapper.md'
  - DaoTokenFactoryType : 'api/classes/DaoTokenFactoryType.md'
  - DaoTokenWrapper : 'api/classes/DaoTokenWrapper.md'
  - DefaultSchemePermissions : 'api/classes/DefaultSchemePermissions.md'
  - EventSubscription : 'api/classes/EventSubscription.md'
  - GenesisDaoCreator : 'api/classes/GenesisDaoCreator.md'
  - GenesisProtocolFactoryType : 'api/classes/GenesisProtocolFactoryType.md'
  - GenesisProtocolWrapper : 'api/classes/GenesisProtocolWrapper.md'
  - GlobalConstraintRegistrarWrapper : 'api/classes/GlobalConstraintRegistrarWrapper.md'
  - IntVoteInterfaceFactoryType : 'api/classes/IntVoteInterfaceFactoryType.md'
  - IntVoteInterfaceWrapper : 'api/classes/IntVoteInterfaceWrapper.md'
  - LoggingService : 'api/classes/LoggingService.md'
  - MintableTokenFactoryType : 'api/classes/MintableTokenFactoryType.md'
  - MintableTokenWrapper : 'api/classes/MintableTokenWrapper.md'
  - PromiseEventService : 'api/classes/PromiseEventService.md'
  - ProposalGeneratorBase : 'api/classes/ProposalGeneratorBase.md'
  - ProposalService : 'api/classes/ProposalService.md'
  - PubSubEventService : 'api/classes/PubSubEventService.md'
  - RedeemerFactoryType : 'api/classes/RedeemerFactoryType.md'
  - RedeemerWrapper : 'api/classes/RedeemerWrapper.md'
  - ReputationFactoryType : 'api/classes/ReputationFactoryType.md'
  - ReputationWrapper : 'api/classes/ReputationWrapper.md'
  - SchemeRegistrarWrapper : 'api/classes/SchemeRegistrarWrapper.md'
  - StandardTokenFactoryType : 'api/classes/StandardTokenFactoryType.md'
  - StandardTokenWrapper : 'api/classes/StandardTokenWrapper.md'
  - SubscriptionCollection : 'api/classes/SubscriptionCollection.md'
  - TokenCapGCWrapper : 'api/classes/TokenCapGCWrapper.md'
  - TransactionService : 'api/classes/TransactionService.md'
  - UpgradeSchemeWrapper : 'api/classes/UpgradeSchemeWrapper.md'
  - Utils : 'api/classes/Utils.md'
  - UtilsInternal : 'api/classes/UtilsInternal.md'
  - VestingSchemeWrapper : 'api/classes/VestingSchemeWrapper.md'
  - VoteInOrganizationSchemeWrapper : 'api/classes/VoteInOrganizationSchemeWrapper.md'
  - Web3EventService : 'api/classes/Web3EventService.md'
  - Web3EventSubscription : 'api/classes/Web3EventSubscription.md'
  - WrapperService : 'api/classes/WrapperService.md'
  - BinaryVoteResult : 'api/enums/BinaryVoteResult.md'
  - ExecutionState : 'api/enums/ExecutionState.md'
  - GlobalConstraintProposalType : 'api/enums/GlobalConstraintProposalType.md'
  - LogLevel : 'api/enums/LogLevel.md'
  - ProposalState : 'api/enums/ProposalState.md'
  - RewardType : 'api/enums/RewardType.md'
  - SchemePermissions : 'api/enums/SchemePermissions.md'
  - SchemeRegistrarProposalType : 'api/enums/SchemeRegistrarProposalType.md'
  - TransactionStage : 'api/enums/TransactionStage.md'
  - UpgradeSchemeProposalType : 'api/enums/UpgradeSchemeProposalType.md'
  - AbsoluteVoteParams : 'api/interfaces/AbsoluteVoteParams.md'
  - AbsoluteVoteParamsResult : 'api/interfaces/AbsoluteVoteParamsResult.md'
  - Agreement : 'api/interfaces/Agreement.md'
  - AgreementBase : 'api/interfaces/AgreementBase.md'
  - AgreementCancelEventResult : 'api/interfaces/AgreementCancelEventResult.md'
  - AgreementProposal : 'api/interfaces/AgreementProposal.md'
  - AgreementProposalEventResult : 'api/interfaces/AgreementProposalEventResult.md'
  - AllowanceOptions : 'api/interfaces/AllowanceOptions.md'
  - ApprovalEventResult : 'api/interfaces/ApprovalEventResult.md'
  - ApproveAndCallOptions : 'api/interfaces/ApproveAndCallOptions.md'
  - ArcWrapperFactories : 'api/interfaces/ArcWrapperFactories.md'
  - ArcWrappers : 'api/interfaces/ArcWrappers.md'
  - ArcWrappersByType : 'api/interfaces/ArcWrappersByType.md'
  - AVVoteProposalEventResult : 'api/interfaces/AVVoteProposalEventResult.md'
  - BurnableTokenBurnOptions : 'api/interfaces/BurnableTokenBurnOptions.md'
  - BurnEventResult : 'api/interfaces/BurnEventResult.md'
  - CancelProposalEventResult : 'api/interfaces/CancelProposalEventResult.md'
  - CancelVotingEventResult : 'api/interfaces/CancelVotingEventResult.md'
  - ChangeApprovalAndCallOptions : 'api/interfaces/ChangeApprovalAndCallOptions.md'
  - ChangeUpgradeSchemeProposalEventResult : 'api/interfaces/ChangeUpgradeSchemeProposalEventResult.md'
  - CollectEventResult : 'api/interfaces/CollectEventResult.md'
  - CollectVestingAgreementConfig : 'api/interfaces/CollectVestingAgreementConfig.md'
  - CommonVestingAgreementConfig : 'api/interfaces/CommonVestingAgreementConfig.md'
  - ContributionProposal : 'api/interfaces/ContributionProposal.md'
  - ContributionRewardParams : 'api/interfaces/ContributionRewardParams.md'
  - ContributionRewardParamsReturn : 'api/interfaces/ContributionRewardParamsReturn.md'
  - ContributionRewardRedeemParams : 'api/interfaces/ContributionRewardRedeemParams.md'
  - ContributionRewardSpecifiedRedemptionParams : 'api/interfaces/ContributionRewardSpecifiedRedemptionParams.md'
  - ControllerAddGlobalConstraintsEventLogEntry : 'api/interfaces/ControllerAddGlobalConstraintsEventLogEntry.md'
  - ControllerRegisterSchemeEventLogEntry : 'api/interfaces/ControllerRegisterSchemeEventLogEntry.md'
  - CreateVestingAgreementConfig : 'api/interfaces/CreateVestingAgreementConfig.md'
  - DaoGlobalConstraintInfo : 'api/interfaces/DaoGlobalConstraintInfo.md'
  - DaoSchemeInfo : 'api/interfaces/DaoSchemeInfo.md'
  - DaoTokenBurnOptions : 'api/interfaces/DaoTokenBurnOptions.md'
  - DaoTokenMintOptions : 'api/interfaces/DaoTokenMintOptions.md'
  - EntityFetcher : 'api/interfaces/EntityFetcher.md'
  - EventFetcher : 'api/interfaces/EventFetcher.md'
  - EventFetcherFilterObject : 'api/interfaces/EventFetcherFilterObject.md'
  - EventHasPropertyId : 'api/interfaces/EventHasPropertyId.md'
  - EventPreProcessorReturn : 'api/interfaces/EventPreProcessorReturn.md'
  - ExecutedGenesisProposal : 'api/interfaces/ExecutedGenesisProposal.md'
  - ExecutedProposal : 'api/interfaces/ExecutedProposal.md'
  - ExecuteProposalEventResult : 'api/interfaces/ExecuteProposalEventResult.md'
  - ForgedDaoInfo : 'api/interfaces/ForgedDaoInfo.md'
  - ForgeOrgConfig : 'api/interfaces/ForgeOrgConfig.md'
  - FounderConfig : 'api/interfaces/FounderConfig.md'
  - GenesisProtocolDaoTokenBalances : 'api/interfaces/GenesisProtocolDaoTokenBalances.md'
  - GenesisProtocolParams : 'api/interfaces/GenesisProtocolParams.md'
  - GenesisProtocolProposal : 'api/interfaces/GenesisProtocolProposal.md'
  - GetAgreementParams : 'api/interfaces/GetAgreementParams.md'
  - GetAllowedRangeOfChoicesResult : 'api/interfaces/GetAllowedRangeOfChoicesResult.md'
  - GetBeneficiaryRewardsParams : 'api/interfaces/GetBeneficiaryRewardsParams.md'
  - GetDaosOptions : 'api/interfaces/GetDaosOptions.md'
  - GetGenesisProtocolParamsResult : 'api/interfaces/GetGenesisProtocolParamsResult.md'
  - GetNumberOfChoicesConfig : 'api/interfaces/GetNumberOfChoicesConfig.md'
  - GetParticipantsOptions : 'api/interfaces/GetParticipantsOptions.md'
  - GetProposalAvatarConfig : 'api/interfaces/GetProposalAvatarConfig.md'
  - GetProposalEventsOptions : 'api/interfaces/GetProposalEventsOptions.md'
  - GetProposalStatusConfig : 'api/interfaces/GetProposalStatusConfig.md'
  - GetProposalStatusResult : 'api/interfaces/GetProposalStatusResult.md'
  - GetRedeemableReputationProposerConfig : 'api/interfaces/GetRedeemableReputationProposerConfig.md'
  - GetRedeemableReputationStakerConfig : 'api/interfaces/GetRedeemableReputationStakerConfig.md'
  - GetRedeemableReputationVoterConfig : 'api/interfaces/GetRedeemableReputationVoterConfig.md'
  - GetRedeemableRewardsStakerConfig : 'api/interfaces/GetRedeemableRewardsStakerConfig.md'
  - GetRedeemableTokensVoterConfig : 'api/interfaces/GetRedeemableTokensVoterConfig.md'
  - GetRedemptionOptions : 'api/interfaces/GetRedemptionOptions.md'
  - GetScoreConfig : 'api/interfaces/GetScoreConfig.md'
  - GetScoreThresholdParamsConfig : 'api/interfaces/GetScoreThresholdParamsConfig.md'
  - GetScoreThresholdParamsResult : 'api/interfaces/GetScoreThresholdParamsResult.md'
  - GetStakerInfoConfig : 'api/interfaces/GetStakerInfoConfig.md'
  - GetStakerInfoResult : 'api/interfaces/GetStakerInfoResult.md'
  - GetStateConfig : 'api/interfaces/GetStateConfig.md'
  - GetThresholdConfig : 'api/interfaces/GetThresholdConfig.md'
  - GetTokenBalancesOptions : 'api/interfaces/GetTokenBalancesOptions.md'
  - GetTokenCapGcParamsResult : 'api/interfaces/GetTokenCapGcParamsResult.md'
  - GetTotalReputationSupplyConfig : 'api/interfaces/GetTotalReputationSupplyConfig.md'
  - GetVoterInfoConfig : 'api/interfaces/GetVoterInfoConfig.md'
  - GetVoterInfoResult : 'api/interfaces/GetVoterInfoResult.md'
  - GetVoteStakeConfig : 'api/interfaces/GetVoteStakeConfig.md'
  - GetVoteStatusConfig : 'api/interfaces/GetVoteStatusConfig.md'
  - GetWinningVoteConfig : 'api/interfaces/GetWinningVoteConfig.md'
  - GPExecuteProposalEventResult : 'api/interfaces/GPExecuteProposalEventResult.md'
  - HasContract : 'api/interfaces/HasContract.md'
  - IBurnableTokenWrapper : 'api/interfaces/IBurnableTokenWrapper.md'
  - IContractWrapperBase : 'api/interfaces/IContractWrapperBase.md'
  - IContractWrapperFactory : 'api/interfaces/IContractWrapperFactory.md'
  - IErc827TokenWrapper : 'api/interfaces/IErc827TokenWrapper.md'
  - IEventSubscription : 'api/interfaces/IEventSubscription.md'
  - IIntVoteInterface : 'api/interfaces/IIntVoteInterface.md'
  - ILogger : 'api/interfaces/ILogger.md'
  - InitializeArcOptions : 'api/interfaces/InitializeArcOptions.md'
  - InitialSchemesSetEventResult : 'api/interfaces/InitialSchemesSetEventResult.md'
  - ITruffleContractFunction : 'api/interfaces/ITruffleContractFunction.md'
  - MintableTokenMintOptions : 'api/interfaces/MintableTokenMintOptions.md'
  - MintEventResult : 'api/interfaces/MintEventResult.md'
  - MintFinishedEventResult : 'api/interfaces/MintFinishedEventResult.md'
  - NewContributionProposalEventResult : 'api/interfaces/NewContributionProposalEventResult.md'
  - NewDaoConfig : 'api/interfaces/NewDaoConfig.md'
  - NewDaoVotingMachineConfig : 'api/interfaces/NewDaoVotingMachineConfig.md'
  - NewGlobalConstraintsProposalEventResult : 'api/interfaces/NewGlobalConstraintsProposalEventResult.md'
  - NewOrgEventResult : 'api/interfaces/NewOrgEventResult.md'
  - NewProposalEventResult : 'api/interfaces/NewProposalEventResult.md'
  - NewSchemeProposalEventResult : 'api/interfaces/NewSchemeProposalEventResult.md'
  - NewUpgradeProposalEventResult : 'api/interfaces/NewUpgradeProposalEventResult.md'
  - NewVestedAgreementEventResult : 'api/interfaces/NewVestedAgreementEventResult.md'
  - NewVoteProposalEventResult : 'api/interfaces/NewVoteProposalEventResult.md'
  - OwnerVoteOptions : 'api/interfaces/OwnerVoteOptions.md'
  - Participant : 'api/interfaces/Participant.md'
  - ProposalDeletedEventResult : 'api/interfaces/ProposalDeletedEventResult.md'
  - ProposalEntity : 'api/interfaces/ProposalEntity.md'
  - ProposalExecutedEventResult : 'api/interfaces/ProposalExecutedEventResult.md'
  - ProposalIdOption : 'api/interfaces/ProposalIdOption.md'
  - ProposalRewards : 'api/interfaces/ProposalRewards.md'
  - ProposeContributionRewardParams : 'api/interfaces/ProposeContributionRewardParams.md'
  - ProposeControllerParams : 'api/interfaces/ProposeControllerParams.md'
  - ProposedVestedAgreementEventResult : 'api/interfaces/ProposedVestedAgreementEventResult.md'
  - ProposeOptions : 'api/interfaces/ProposeOptions.md'
  - ProposeToAddModifyGlobalConstraintParams : 'api/interfaces/ProposeToAddModifyGlobalConstraintParams.md'
  - ProposeToAddModifySchemeParams : 'api/interfaces/ProposeToAddModifySchemeParams.md'
  - ProposeToRemoveGlobalConstraintParams : 'api/interfaces/ProposeToRemoveGlobalConstraintParams.md'
  - ProposeToRemoveSchemeParams : 'api/interfaces/ProposeToRemoveSchemeParams.md'
  - ProposeUpgradingSchemeParams : 'api/interfaces/ProposeUpgradingSchemeParams.md'
  - ProposeVestingAgreementConfig : 'api/interfaces/ProposeVestingAgreementConfig.md'
  - RedeemConfig : 'api/interfaces/RedeemConfig.md'
  - RedeemerOptions : 'api/interfaces/RedeemerOptions.md'
  - RedeemerRedeemEventResult : 'api/interfaces/RedeemerRedeemEventResult.md'
  - RedeemEventResult : 'api/interfaces/RedeemEventResult.md'
  - RedemptionResult : 'api/interfaces/RedemptionResult.md'
  - RefreshReputationEventResult : 'api/interfaces/RefreshReputationEventResult.md'
  - RemoveGlobalConstraintsProposalEventResult : 'api/interfaces/RemoveGlobalConstraintsProposalEventResult.md'
  - RemoveSchemeProposalEventResult : 'api/interfaces/RemoveSchemeProposalEventResult.md'
  - ReputationBurnEventResult : 'api/interfaces/ReputationBurnEventResult.md'
  - ReputationBurnOptions : 'api/interfaces/ReputationBurnOptions.md'
  - ReputationMintEventResult : 'api/interfaces/ReputationMintEventResult.md'
  - ReputationMintOptions : 'api/interfaces/ReputationMintOptions.md'
  - RevokeSignToCancelAgreementEventResult : 'api/interfaces/RevokeSignToCancelAgreementEventResult.md'
  - RevokeSignToCancelVestingAgreementConfig : 'api/interfaces/RevokeSignToCancelVestingAgreementConfig.md'
  - SchemeConfig : 'api/interfaces/SchemeConfig.md'
  - SchemeProposalExecuted : 'api/interfaces/SchemeProposalExecuted.md'
  - SchemeProposalExecutedEventResult : 'api/interfaces/SchemeProposalExecutedEventResult.md'
  - SchemeRegistrarParams : 'api/interfaces/SchemeRegistrarParams.md'
  - SchemesConfig : 'api/interfaces/SchemesConfig.md'
  - SchemeWrapper : 'api/interfaces/SchemeWrapper.md'
  - SetSchemesConfig : 'api/interfaces/SetSchemesConfig.md'
  - ShouldBoostConfig : 'api/interfaces/ShouldBoostConfig.md'
  - SignToCancelAgreementEventResult : 'api/interfaces/SignToCancelAgreementEventResult.md'
  - SignToCancelVestingAgreementConfig : 'api/interfaces/SignToCancelVestingAgreementConfig.md'
  - StakeConfig : 'api/interfaces/StakeConfig.md'
  - StakeEventResult : 'api/interfaces/StakeEventResult.md'
  - StandardSchemeParams : 'api/interfaces/StandardSchemeParams.md'
  - StandardTokenAllowanceOptions : 'api/interfaces/StandardTokenAllowanceOptions.md'
  - StandardTokenApproveOptions : 'api/interfaces/StandardTokenApproveOptions.md'
  - StandardTokenChangeApprovalOptions : 'api/interfaces/StandardTokenChangeApprovalOptions.md'
  - StandardTokenTransferFromOptions : 'api/interfaces/StandardTokenTransferFromOptions.md'
  - StandardTokenTransferOptions : 'api/interfaces/StandardTokenTransferOptions.md'
  - TokenCapGcParams : 'api/interfaces/TokenCapGcParams.md'
  - TransactionReceiptsEventInfo : 'api/interfaces/TransactionReceiptsEventInfo.md'
  - TransactionReceiptTruffle : 'api/interfaces/TransactionReceiptTruffle.md'
  - TransferAndCallOptions : 'api/interfaces/TransferAndCallOptions.md'
  - TransferEventResult : 'api/interfaces/TransferEventResult.md'
  - TransferFromAndCallOptions : 'api/interfaces/TransferFromAndCallOptions.md'
  - TruffleContract : 'api/interfaces/TruffleContract.md'
  - VestingSchemeSchemeProposalExecuted : 'api/interfaces/VestingSchemeSchemeProposalExecuted.md'
  - VotableGlobalConstraintProposal : 'api/interfaces/VotableGlobalConstraintProposal.md'
  - VotableProposal : 'api/interfaces/VotableProposal.md'
  - VotableSchemeRegistrarProposal : 'api/interfaces/VotableSchemeRegistrarProposal.md'
  - VotableUpgradeSchemeProposal : 'api/interfaces/VotableUpgradeSchemeProposal.md'
  - VotableVoteInOrganizationProposal : 'api/interfaces/VotableVoteInOrganizationProposal.md'
  - VoteInOrganizationProposeVoteConfig : 'api/interfaces/VoteInOrganizationProposeVoteConfig.md'
  - VoteOnBehalfEventResult : 'api/interfaces/VoteOnBehalfEventResult.md'
  - VoteOptions : 'api/interfaces/VoteOptions.md'
  - VoteProposalEventResult : 'api/interfaces/VoteProposalEventResult.md'
  - VoteStatusOptions : 'api/interfaces/VoteStatusOptions.md'
  - VoteWithSpecifiedAmountsOptions : 'api/interfaces/VoteWithSpecifiedAmountsOptions.md'
  - Web3EventFetcher : 'api/interfaces/Web3EventFetcher.md'
  - WrapperFilter : 'api/interfaces/WrapperFilter.md'
  - WrapperServiceInitializeOptions : 'api/interfaces/WrapperServiceInitializeOptions.md'
